<?php

/* custom routes generated by CRUD */


Route::group(array('middleware' => 'admin'), function () {

Route::get('personas', ['as'=> 'personas.index', 'uses' => 'PersonaController@index']);
Route::post('personas', ['as'=> 'personas.store', 'uses' => 'PersonaController@store']);
Route::get('personas/create', ['as'=> 'personas.create', 'uses' => 'PersonaController@create']);
Route::put('personas/{personas}', ['as'=> 'personas.update', 'uses' => 'PersonaController@update']);
Route::patch('personas/{personas}', ['as'=> 'personas.update', 'uses' => 'PersonaController@update']);
Route::get('personas/{id}/delete', array('as' => 'personas.delete', 'uses' => 'PersonaController@getDelete'));
Route::get('personas/{id}/confirm-delete', array('as' => 'personas.confirm-delete', 'uses' => 'PersonaController@getModalDelete'));
Route::get('personas/{personas}', ['as'=> 'personas.show', 'uses' => 'PersonaController@show']);
Route::get('personas/{personas}/edit', ['as'=> 'personas.edit', 'uses' => 'PersonaController@edit']);

});
